---
title: "Executive Summary"
author: "Max Spehlmann"
date: "`r Sys.Date()`"
output: 
  html_document
---


<!-- 
Step one:

Import microbiology and water chemistry data

-->


```{r setup_and_import, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load necessary packages
library(tidyverse)
library(here)
library(ggthemes)
library(ggprism)

#Set a ggplot theme
theme_set(theme_minimal(base_size = 12, base_family = "Times"))

#import water quality data
Meta_Data <- read_csv(here("data", "meta_data.csv"),
                      col_types = cols(Collection_Date = col_date(format = "%m/%d/%y"))) %>% mutate(Station_Num = fct_relevel(Station_Num, "Post Filtration", "Post Chlorination", "Finished Water", "1", "3", "4", "5")) %>%
               mutate(distance_from_plant_km = round(miles_from_plant*1.61,2)) %>% mutate(Location_Clean = fct_relevel(Location_Clean, "Treatment Plant", "Stn. 1", "Stn. 3", "Stn. 4", "Stn. 5"))
```

### Characterizing the water chemistry of the Whitefish Bay, Wisconsin water service district


```{r descriptive_water_quality}
#For analyte boxplots:
for_analyte_boxplots <- Meta_Data %>% select(sample_name_abridged, Station_Num, Collection_Date, Sp_Cond_us_cm:pH, Chlorine_Free_mg_L, distance_from_plant_km) %>%  
  gather(analyte, value, -c(sample_name_abridged, Station_Num, Collection_Date, distance_from_plant_km)) %>% mutate(Station_Num = fct_relevel(Station_Num, "Post Filtration", "Finished Water", "5", "4", "3", "1")) %>% filter(!(Station_Num %in% c("Finished Water",
                              "Post Filtration", "Post Chlorination")))

chlorine_plot <- for_analyte_boxplots %>%
 filter(analyte %in% "Chlorine_Free_mg_L") %>%
 ggplot() +
 aes(x = analyte, y = value, fill = Station_Num) +
 geom_boxplot() +
 scale_fill_brewer(palette = "Paired", guide = guide_legend(reverse = TRUE)) +
 labs(y = expression(paste("Free Chlorine (mg L"^{-1}, ")")), fill = "Station #") +
   theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y =element_blank()) +
  coord_flip()

conductivity_plot <- for_analyte_boxplots %>%
  filter(analyte %in% "Sp_Cond_us_cm") %>%
  filter(value >= 300 & value <= 320) %>%
  ggplot() +
  aes(x = analyte, y = value, fill = Station_Num) +
  geom_boxplot() +
  scale_fill_brewer(palette = "Paired", guide = guide_legend(reverse = TRUE)) +
  labs(y = "Specific Conductivity (\u00b5s/m\u00b2)", fill = "Station #") +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  coord_flip() 

water_temp_plot <- for_analyte_boxplots %>%
  filter(analyte %in% "Water_Temp_C") %>%
  ggplot() +
  aes(x = analyte, y = value, fill = Station_Num) +
  geom_boxplot() +
  scale_fill_brewer(palette = "Paired", guide = guide_legend(reverse = TRUE)) +
  labs(y = "Water Temp. (C)", fill = "Station #") +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  coord_flip() 

dO_plot <- for_analyte_boxplots %>%
  filter(analyte %in% "DO_mg_L") %>%
  ggplot() +
  aes(x = analyte, y = value, fill = Station_Num) +
  geom_boxplot() +
  scale_fill_brewer(palette = "Paired", guide = guide_legend(reverse = TRUE)) +
  labs(y = expression(paste("Dissolved Oxygen (mg L"^{-1}, ")")), fill = "Station #") +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  coord_flip() 

pH_plot <- for_analyte_boxplots %>%
  filter(analyte %in% "pH") %>%
  ggplot() +
  aes(x = analyte, y = value, fill = Station_Num) +
  geom_boxplot() +
  scale_fill_brewer(palette = "Paired", guide = guide_legend(reverse = TRUE)) +
  labs(y = "pH", fill = "Station #") +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  coord_flip() 



main <- cowplot::plot_grid(chlorine_plot + theme(legend.position = "none"), 
                          conductivity_plot + theme(legend.position = "none"),
                          water_temp_plot + theme(legend.position = "none"),
                          dO_plot + theme(legend.position = "none"),
                          pH_plot + theme(legend.position = "none"))

main <- cowplot::plot_grid(main, cowplot::get_legend(chlorine_plot + theme(legend.box.margin = margin(0, 0, 0, 12))), ncol=2, rel_widths = c(2, .4))

main
```

### Free Chlorine Measurements by Date Sampled and Location



```{r free_chlorine, echo=FALSE}
chlorine_scatter_plot <- for_analyte_boxplots %>%
  filter(analyte %in% "Chlorine_Free_mg_L") %>%
  ggplot() +
  aes(x = distance_from_plant_km, y = value, label = Station_Num) +
  geom_point(size = 2) +
  labs(y = expression(paste("Free Chlorine (mg L"^{-1}, ")")), x = "Distance From Plant (km)") +
  scale_y_continuous(limits = c(0,.4), breaks = seq(0, .4,.1)) +
  facet_wrap(facets = vars(Collection_Date), labeller = function(x) format(x, '%m/%d/%Y'))
  
chlorine_scatter_plot
```


```{r Figure5, out.width= "60%", fig.width=5.14, warning=FALSE, message=FALSE}
df_p_val <- rstatix::t_test(Meta_Data, cell_concentration_cell_mL ~ Location_Clean, ref.group = "Treatment Plant") %>% 
  rstatix::add_xy_position()


n_fun <- function(x){
  return(data.frame(y = 1.05E5, label = paste0("n = ",length(x))))
}

ggplot(Meta_Data, (aes(x = Location_Clean, y = cell_concentration_cell_mL))) +
  stat_summary(fun = mean, geom = "bar", color = "black", fill = c('#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99')) + 
  stat_summary(fun.data = mean_cl_boot, geom = "errorbar", show.legend = FALSE, width = .5) +
  labs(x = NULL) + scale_y_continuous(labels = scales::scientific) +
  ylab(expression(paste("Cell Concentration (cell ml"^{-1}, ")"))) + 
  add_pvalue(df_p_val, 
             label = "p = {p.adj}",
             remove.bracket = TRUE,
             y.position = 1.0e5) +
  stat_summary(fun.data = n_fun, geom = "text")

```